base: &common
  site: http://example.com
  analytics_id: UA-10385211-1
  analytics_vendor: googlean
  session_key: _shapado_session
  session_secret: 9ac4fd97a52153070a0bd47467c00eded1badf526f145827384ddfde45ac0bfd3f0230c961ddfb9ef84d490b3d889e0169de8eee3ef7b7ed114262824f8aa8aa
  rest_auth_key: b4d66d73a1ade79ce227fba01b33f2ab021888ef
  rest_auth_digest_stretches: 10
  enable_sharing: true
  notification_email: notifications@example.com
  default_language: en
  adbard_host_id: 2746b6d24c93f71df12503ec2ab667e5
  adbard_site_key: e8e24a6b2cba51145dc0c874e1b2f4a4
  application_name: Shapado
  is_shapadocom: false
  enable_groups: false
  default_language: en
  enable_i18n: false

  exception_notification:
    activate: true
    exception_sender_address:
      "[Shapado] error notifier <error-notifier@example.com>"
    exception_recipients:
    - admin@example.com

development:
  <<: *common
  domain: localhost.lan
production:
  <<: *common
  domain: example.com
  googlean_domain: .shapado.com
test:
  <<: *common
  domain: test.loc

